[package]
name = "l"
version = "0.7.30"
authors = ["zzzzzzzzzzz <zzzzzzzzzzzgg@gmail.com>"]
edition = "2018"

[lib]
name = "l4"
crate-type = ["cdylib"]

[dependencies]
zhscript2 = {version = "0.7.30", path = "../zhscript2-rust", features = ["thread"]}
zs2_l4_ = {version = "0.7.30", path = "../zs2-l4-rust"}
libloading = "0.5.0"
