[package]
name = "l"
version = "0.6.5"
authors = ["zzzzzzzzzzz <zzzzzzzzzzzgg@gmail.com>"]
edition = "2018"

[lib]
name = "l4"
crate-type = ["dylib"]

[dependencies]
zhscript2 = {version = "0.6.5", path = "../zhscript2-rust", features = ["thread"]}
libloading = "0.5.0"
rusty-asm = "0.2.1"
